env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
    #rclone_config: "ENCRYPTED[84378bb65c63f2d8176c7aac3d1210e5c957dbe8ec383833510c6bcee32a7c2202b38de9b6bc7cc7463b9c8523a9e154]"

task:
    name: John
    timeout_in: 25m
    container:
      image: apon77/aosp:latest
      cpu: 6
      memory: 8G
   # download_ccache_background_script:
   #   - ./download_ccache
    sync_script:
      - ./sync
    build_script:
      - ./build
    #upload_ccache_script:
    #  - ./upload_ccache
