#!/bin/bash
cd /tmp/kernel/Logan*
#cd /tmp/aex 
#rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Normal build steps
#. build/envsetup.sh
#lunch aosp_ysl-userdebug
#export SELINUX_IGNORE_NEVERALLOWS=true

# Kernel Build
export ARCH=arm64 
export SUBARCh=arm64
export KBUILD_BUILD_USER=noob-214
export KBUILD_BUILD_HOST=ubuntu
export CROSS_COMPILE=../gcc64/bin/aarch64-elf-
export CROSS_COMPILE_ARM32=../gcc32/bin/arm-eabi-
# export PATH="/tmp/kernel/proton-clang/bin:$PATH"
mkdir ../out
make O=../out ysl-perf_defconfig ARCH=arm64 -j6 
make O=../out ARCH=arm64 -j6 EXTRAVERSION=MaD  

# CROSS_COMPILE=aarch64-linux-gnu- CC=clang CROSS_COMPILE_ARM32=arm-linux-gnueabi- EXTRAVERSION=MaD && sleep 10m

# upload function for uploading rom zip file! I don't want unwanted builds in my google drive haha!
# Telgram env setup
#API_BOT=1768732147:AAFwOH-C3FETGF5GO6Hu0J0-OwEtelXpDSg
#CHATID=1001470828701
#export BOT_MSG_URL="https://api.telegram.org/bot$API_BOT/sendMessage"
#export BOT_BUILD_URL="https://api.telegram.org/bot$API_BOT/sendDocument"

#tg_post_msg() {
#        curl -s -X POST "$BOT_MSG_URL" -d chat_id="$2" \
#       -d "parse_mode=html" \
#        -d text="$1"
#}

# stuffs
#up(){
#	curl --upload-file $1 https://transfer.sh/
#}

#make_metalava(){
#	m api-stubs-docs
#	m system-api-stubs-docs
#	m test-api-stubs-docs
#}

#make_rom(){
#	tg_post_msg "<b>Build Triggered for ysl</b>" "$CHATID"
#	m aex -j14
#	url=$(up out/target/product/ysl/*zip)
#	echo " "
#	echo "$url"
#	tg_post_msg "<b>Build Completed</b>%0A%0A<b>Link : </b> <code>"$url"</code>" "$CHATID"
#}

#make_metalava #34
#make_rom
cd ../out/arch/arm64/boot
curl bashupload.com/logan.gz --data-binary @Image.gz-dtb


