#!/bin/bash

#MANIFEST=https://github.com/AospExtended/manifest
#BRANCH=11.x

#mkdir -p /tmp/aex # Where to sync source
#cd /tmp/aex
mkdir -p /tmp/kernel
#setup
sudo apt-get install -y bc python-dev flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip
#repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault

#git config --global user.name noob-214
#git config --global user.email sandeeps567ingh@gmail.com

# sync
#repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

#cloning
# Sync stuffs
#find hardware/qcom-caf/msm8996/display hardware/qcom-caf/msm8996/audio hardware/qcom-caf/msm8996/media vendor/codeaurora/telephony/ .repo/ -delete

#git clone https://github.com/wave-project/vendor_codeaurora_telephony --depth=1 --single-branch vendor/codeaurora/telephony/
#git clone https://github.com/Jabiyeff/android_hardware_qcom_media --depth=1 --single-branch hardware/qcom-caf/msm8996/media
#git clone https://github.com/Jabiyeff/android_hardware_qcom_display --depth=1 --single-branch hardware/qcom-caf/msm8996/display
#git clone https://github.com/LineageOS/android_hardware_qcom_audio --depth=1 --single-branch -b lineage-18.1-caf-msm8996 hardware/qcom-caf/msm8996/audio

#git clone https://github.com/Noob-214/device_xiaomi_ysl_enforcing --depth=1 device/xiaomi/ysl
#git clone https://github.com/Noob-214/Logan_Ysl -b Stable --depth=1 kernel/xiaomi/ysl
#git clone https://github.com/ItsVixano/android_vendor_xiaomi_ysl --depth=1 -b r11.0 vendor/xiaomi/ysl
#git clone https://github.com/lineageos/android\_packages\_resources\_devicesettings packages/resources/devicesettings  --depth=1

# kernel
#mkdir -p /tmp/kernel # Where to sync source
cd /tmp/kernel
git clone https://github.com/Noob-214/Logan_Ysl -b MaD --depth=1 -j8
# Clang
#cd Log*
# git clone https://github.com/kdrag0n/proton-clang --depth=1 -j8
# git clone https://github.com/Noob-214/android_kernel_xiaomi_msm8937-4.9 --depth=1 android
git clone https://github.com/TwistedPrime/twisted-clang --depth=1 -j8 
# Gcc
#git clone https://github.com/mvaisakh/gcc-arm64 --depth=1 -j8 gcc64
#git clone https://github.com/mvaisakh/gcc-arm --depth=1 -j8 gcc32

